name: Build

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: actions/cache@v4
      id: node-modules
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-
    - run: npm install
    - run: npm run check
    - run: PUBLIC_URL=/twitch-vod-sync/ npm run build
    - run: npm run test
    - run: echo ${{ github.ref }}
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
      if: ${{ github.ref == 'refs/heads/master' }}
